DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY auto_increment,
    NAME VARCHAR(255),
    AUTHOR BIGINT REFERENCES AUTHOR(ID),
    GENRE BIGINT REFERENCES GENRE(ID),
    foreign key (GENRE) references GENRE(id) on delete cascade,
    foreign key (AUTHOR) references AUTHOR(id) on delete cascade);
