DROP TABLE IF EXISTS AUTHOR;
CREATE TABLE AUTHOR(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS GENRE;
CREATE TABLE GENRE(ID BIGINT PRIMARY KEY auto_increment, NAME VARCHAR(255));

DROP TABLE IF EXISTS BOOKS;
CREATE TABLE BOOKS(
    ID BIGINT PRIMARY KEY auto_increment,
    NAME VARCHAR(255),
    AUTHOR_ID BIGINT REFERENCES AUTHOR(ID),
    GENRE_ID BIGINT REFERENCES GENRE(ID),
    foreign key (GENRE_ID) references GENRE(id) on delete cascade,
    foreign key (AUTHOR_ID) references AUTHOR(id) on delete cascade);
